
version: '3.8'

services:
  # Frontend React application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    restart: unless-stopped

  # Supabase Edge Functions service (development only)
  # For production, use Supabase hosting for Edge Functions
  supabase-functions:
    image: supabase/edge-functions:latest
    ports:
      - "54321:9000"
    volumes:
      - ./supabase/functions:/home/deno/functions
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    depends_on:
      - app
    restart: unless-stopped

volumes:
  db_data:
