
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    restart: unless-stopped
    networks:
      - app-network

  # Supabase Edge Functions
  supabase-functions:
    build:
      context: ./supabase/functions
      dockerfile: Dockerfile.functions
    ports:
      - "54321:54321"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    volumes:
      - ./supabase:/app/supabase
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
