// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycjmaxrexzzclhvgynwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inljam1heHJleHp6Y2xodmd5bndyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MTE1NDQsImV4cCI6MjA1NzE4NzU0NH0.1WpYuBnjP1AouBS61OLrnJKRC8dbaVoT0Bs4GAWR2hg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);